healmessage: You have been healed
couldnotfind: Coudnt find the player
feedmessage: You have been fed
vanish: You have been vanished!
unvanish: You have been unvanished!
sun: Cleared the clouds, killed the rain!
flymessage: Enabled flymode!
nospawn: Coudnt find the spawn!
spawnwelcome: Welcome to the spawn!